[window]
    padding = { x = 5 }
    option_as_alt = "None"
    decorations = "Full"
    dynamic_padding = true

[scrolling]
    history = 60000
    multiplier = 3

[font]
    size = 18

[font.normal]
    family = "JetBrainsMono Nerd Font Mono"

[selection]
    save_to_clipboard = true

[cursor]
    vi_mode_style = "Block"
    blink_interval = 750
    unfocused_hollow = true

[cursor.style]
    shape = "Block"
    blinking = "On"

[env]
TERM = "xterm-256color"

[general]
live_config_reload = true

import = ["~/.config/alacritty/tokyonight/tokyonight-moon.toml"]
